# Generated by Django 3.2 on 2023-11-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image_path',
        ),
    ]
