# Generated by Django 3.2 on 2023-11-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_remove_map_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_description',
            field=models.CharField(choices=[(1, 'Red'), (2, 'Orange'), (3, 'Yellow'), (4, 'Green'), (5, 'Blue'), (6, 'Indigo'), (7, 'Violet'), (8, 'Black'), (9, 'White')], max_length=15),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.IntegerField(choices=[(1, 'Red'), (2, 'Orange'), (3, 'Yellow'), (4, 'Green'), (5, 'Blue'), (6, 'Indigo'), (7, 'Violet'), (8, 'Black'), (9, 'White')], primary_key=True, serialize=False),
        ),
    ]
